---
# download
k3s_version: v1.24.4+k3s1

# k3s master/nodes
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"

# geerlingguy.raspberry-pi
raspberry_pi_boot_config_options:
  # Set the GPU memory split value.
  - regexp: "^#?gpu_mem"
    line: "gpu_mem=16"
  # Disable wi-fi
  - regexp: "^dtoverlay=disable-wifi"
    line: "dtoverlay=disable-wifi"
  # Disable bluetooth
  - regexp: "^dtoverlay=disable-bt"
    line: "dtoverlay=disable-bt"
  # Set gpio fan pin and temp
  - regexp: "^#?dtoverlay=gpio-fan,gpiopin"
    line: "dtoverlay=gpio-fan,gpiopin=3,temp=65000"
  # Set poe fan level 0
  - regexp: "^#?dtparam=poe_fan_temp0"
    line: "dtparam=poe_fan_temp0=50000"
  # Set poe fan level 1
  - regexp: "^#?dtparam=poe_fan_temp1"
    line: "dtparam=poe_fan_temp1=60000"
  # Set poe fan level 2
  - regexp: "^#?dtparam=poe_fan_temp2"
    line: "dtparam=poe_fan_temp2=70000"
  # Set poe fan level 3
  - regexp: "^#?dtparam=poe_fan_temp3"
    line: "dtparam=poe_fan_temp3=80000"
