---
raspberry_pi_rc_local_options:
  # Disable HDMI on startup (for power savings).
  - regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"

# escalate.dhcpcd
dhcpcd_static_ipv4_configuration_enabled: true
dhcpcd_static_ipv4_address: "{{ ansible_default_ipv4.address }}/24"
dhcpcd_static_ipv4_gateway: "192.168.2.1"
dhcpcd_static_ipv4_domain_name_server: "1.1.1.1 1.0.0.1"

# jnv.unattended-upgrades
unattended_origins_patterns:
  - "origin=Raspbian,codename=${distro_codename},label=Raspbian"
  - "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation"

# robertdebock.rsyslog
rsyslog_mods:
  - imuxsock
  - imklog

rsyslog_remote: "192.168.2.242"
rsyslog_remote_selector: "*.*"
rsyslog_remote_tcp: no
rsyslog_remote_port: 514

rsyslog_fileowner: "root"
rsyslog_filegroup: "adm"

rsyslog_dircreatemode: "0755"
rsyslog_filecreatemode: "0640"
rsyslog_umask: "0022"

rsyslog_default_rules:
  - {rule: 'auth,authpriv.*', logpath: '/var/log/auth.log'}
  - {rule: '*.*;auth,authpriv.none', logpath: '-/var/log/syslog'}
  - {rule: '#cron.*', logpath: '/var/log/cron.log'}
  - {rule: 'daemon.*', logpath: '-/var/log/daemon.log'}
  - {rule: 'kern.*', logpath: '-/var/log/kern.log'}
  - {rule: 'lpr.*', logpath: '-/var/log/lpr.log'}
  - {rule: 'mail.*', logpath: '-/var/log/mail.log'}
  - {rule: 'user.*', logpath: '-/var/log/user.log'}

  - {rule: 'mail.info', logpath: '-/var/log/mail.info'}
  - {rule: 'mail.warn', logpath: '-/var/log/mail.warn'}
  - {rule: 'mail.err', logpath: '/var/log/mail.err'}

  - {rule: '*.=debug;auth,authpriv.none;mail.none', logpath: '-/var/log/debug'}
  - {rule: '*.=info;*.=notice;*.=warn;auth,authpriv.none;cron,daemon.none;mail.none', logpath: '-/var/log/messages'}

  - {rule: '*.emerg', logpath: ':omusrmsg:*'}
