---
raspberry_pi_rc_local_options:
  # Disable HDMI on startup (for power savings).
  - regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"

# escalate.dhcpcd
dhcpcd_static_ipv4_configuration_enabled: true
dhcpcd_static_ipv4_address: "{{ ansible_default_ipv4.address }}/24"
dhcpcd_static_ipv4_gateway: "192.168.2.1"
dhcpcd_static_ipv4_domain_name_server: "1.1.1.1 1.0.0.1"

# jnv.unattended-upgrades
unattended_origins_patterns:
  - "origin=Raspbian,codename=${distro_codename},label=Raspbian"
  - "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation"
