---
# geerlingguy.raspberry-pi
raspberry_pi_boot_config_options:
  # Set the GPU memory split value.
  - regexp: "^#?gpu_mem"
    line: "gpu_mem=16"
  # Disable wi-fi
  - regexp: "^dtoverlay=disable-wifi"
    line: "dtoverlay=disable-wifi"
  # Disable bluetooth
  - regexp: "^dtoverlay=disable-bt"
    line: "dtoverlay=disable-bt"
  # Disable Power LED
  - regexp: "^dtparam=pwr_led_trigger=none"
    line: "dtparam=pwr_led_trigger=none"
  # Disable Activity LED
  - regexp: "^dtparam=act_led_trigger=none"
    line: "dtparam=act_led_trigger=none"

# geerlingguy.docker
docker_compose_arch: "aarch64"
docker_apt_arch: "arm64"

# artis3n.tailscale
tailscale_args: "--advertise-exit-node --advertise-routes=192.168.2.0/24"

# ironicbadger.docker_compose_generator
appdata_path: /home/{{ ansible_user }}/appdata
docker_compose_generator_output_path: /home/{{ ansible_user }}

containers:
  ###
  - service_name: swag
    active: true
    image: linuxserver/swag
    ports:
      - 80:80/tcp 
      - 443:443/tcp 
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - URL={{ swag_url }}
      - VALIDATION=dns
      - SUBDOMAINS={{ swag_subdomains }}
      - DNSPLUGIN=cloudflare
      - EMAIL={{ acme_email }}
      - ONLY_SUBDOMAINS=true
    volumes:
      - "{{ appdata_path }}/swag/config:/config"
    restart: unless-stopped
  ###
  - service_name: adguard
    active: true
    depends_on:
      - swag
    image: adguard/adguardhome:v0.107.8
    ports:
      - 53:53/udp
    volumes:
      - "{{ appdata_path }}/adguardhome/workdir:/opt/adguardhome/work"
      - "{{ appdata_path }}/adguardhome/conf:/opt/adguardhome/conf"
    restart: unless-stopped
