---
collections:
  - community.docker

roles:
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: geerlingguy.docker
    version: 5.2.1
  - name: geerlingguy.raspberry-pi
    version: 1.2.0
  - name: jnv.unattended-upgrades
    version: v1.12.2
  - name: escalate.dhcpcd
    version: v1.2.0
  - name: escalate.swap
    version: v1.1.0
  - name: juju4.ipv6
    version: 1.5.0
  - name: ironicbadger.docker_compose_generator
    version: 1.0.4
  - name: artis3n.tailscale
    version: v3.2.3
  - name: robertdebock.rsyslog
    version: 4.6.1
  - name: geerlingguy.pip
    version: 2.2.0
