---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: geerlingguy.raspberry-pi
    - role: escalate.swap
    - role: escalate.dhcpcd
    - role: jnv.unattended-upgrades
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nfs
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node