---

- hosts: raspberry_pi
  gather_facts: true
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: geerlingguy.raspberry-pi
    - role: escalate.dhcpcd
    - role: jnv.unattended-upgrades
    - role: robertdebock.rsyslog

- hosts: k3s_cluster
  gather_facts: true
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: juju4.ipv6
    - role: prereq
    - role: escalate.swap
    - role: download
    - role: raspberrypi

- hosts: k3s_master
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: geerlingguy.nfs
    - role: k3s/master

- hosts: k3s_node
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: k3s/node

- hosts: vpn_relay
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: artis3n.tailscale
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
    - role: geerlingguy.pip
    - role: cloudflare
      become: false
  tasks:
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}
        pull: true
        recreate: always
